/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.12.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.mic.nifi.swagger.client.model;

import java.util.Objects;
import at.mic.nifi.swagger.client.model.ConnectionStatisticsSnapshotDTO;
import at.mic.nifi.swagger.client.model.NodeConnectionStatisticsSnapshotDTO;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ConnectionStatisticsDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-05T15:38:14.826+01:00")
public class ConnectionStatisticsDTO {
  @SerializedName("id")
  private String id = null;

  @SerializedName("statsLastRefreshed")
  private String statsLastRefreshed = null;

  @SerializedName("aggregateSnapshot")
  private ConnectionStatisticsSnapshotDTO aggregateSnapshot = null;

  @SerializedName("nodeSnapshots")
  private List<NodeConnectionStatisticsSnapshotDTO> nodeSnapshots = new ArrayList<NodeConnectionStatisticsSnapshotDTO>();

  public ConnectionStatisticsDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the connection
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "The ID of the connection")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ConnectionStatisticsDTO statsLastRefreshed(String statsLastRefreshed) {
    this.statsLastRefreshed = statsLastRefreshed;
    return this;
  }

   /**
   * The timestamp of when the stats were last refreshed
   * @return statsLastRefreshed
  **/
  @ApiModelProperty(example = "null", value = "The timestamp of when the stats were last refreshed")
  public String getStatsLastRefreshed() {
    return statsLastRefreshed;
  }

  public void setStatsLastRefreshed(String statsLastRefreshed) {
    this.statsLastRefreshed = statsLastRefreshed;
  }

  public ConnectionStatisticsDTO aggregateSnapshot(ConnectionStatisticsSnapshotDTO aggregateSnapshot) {
    this.aggregateSnapshot = aggregateSnapshot;
    return this;
  }

   /**
   * The status snapshot that represents the aggregate stats of the cluster
   * @return aggregateSnapshot
  **/
  @ApiModelProperty(example = "null", value = "The status snapshot that represents the aggregate stats of the cluster")
  public ConnectionStatisticsSnapshotDTO getAggregateSnapshot() {
    return aggregateSnapshot;
  }

  public void setAggregateSnapshot(ConnectionStatisticsSnapshotDTO aggregateSnapshot) {
    this.aggregateSnapshot = aggregateSnapshot;
  }

  public ConnectionStatisticsDTO nodeSnapshots(List<NodeConnectionStatisticsSnapshotDTO> nodeSnapshots) {
    this.nodeSnapshots = nodeSnapshots;
    return this;
  }

  public ConnectionStatisticsDTO addNodeSnapshotsItem(NodeConnectionStatisticsSnapshotDTO nodeSnapshotsItem) {
    this.nodeSnapshots.add(nodeSnapshotsItem);
    return this;
  }

   /**
   * A list of status snapshots for each node
   * @return nodeSnapshots
  **/
  @ApiModelProperty(example = "null", value = "A list of status snapshots for each node")
  public List<NodeConnectionStatisticsSnapshotDTO> getNodeSnapshots() {
    return nodeSnapshots;
  }

  public void setNodeSnapshots(List<NodeConnectionStatisticsSnapshotDTO> nodeSnapshots) {
    this.nodeSnapshots = nodeSnapshots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionStatisticsDTO connectionStatisticsDTO = (ConnectionStatisticsDTO) o;
    return Objects.equals(this.id, connectionStatisticsDTO.id) &&
        Objects.equals(this.statsLastRefreshed, connectionStatisticsDTO.statsLastRefreshed) &&
        Objects.equals(this.aggregateSnapshot, connectionStatisticsDTO.aggregateSnapshot) &&
        Objects.equals(this.nodeSnapshots, connectionStatisticsDTO.nodeSnapshots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, statsLastRefreshed, aggregateSnapshot, nodeSnapshots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionStatisticsDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    statsLastRefreshed: ").append(toIndentedString(statsLastRefreshed)).append("\n");
    sb.append("    aggregateSnapshot: ").append(toIndentedString(aggregateSnapshot)).append("\n");
    sb.append("    nodeSnapshots: ").append(toIndentedString(nodeSnapshots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

