/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.12.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.mic.nifi.swagger.client.model;

import java.util.Objects;
import at.mic.nifi.swagger.client.model.AffectedComponentEntity;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ParameterDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-05T15:38:14.826+01:00")
public class ParameterDTO {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sensitive")
  private Boolean sensitive = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("referencingComponents")
  private List<AffectedComponentEntity> referencingComponents = new ArrayList<AffectedComponentEntity>();

  public ParameterDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the Parameter
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The name of the Parameter")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ParameterDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the Parameter
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "The description of the Parameter")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ParameterDTO sensitive(Boolean sensitive) {
    this.sensitive = sensitive;
    return this;
  }

   /**
   * Whether or not the Parameter is sensitive
   * @return sensitive
  **/
  @ApiModelProperty(example = "null", value = "Whether or not the Parameter is sensitive")
  public Boolean getSensitive() {
    return sensitive;
  }

  public void setSensitive(Boolean sensitive) {
    this.sensitive = sensitive;
  }

  public ParameterDTO value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value of the Parameter
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "The value of the Parameter")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public ParameterDTO referencingComponents(List<AffectedComponentEntity> referencingComponents) {
    this.referencingComponents = referencingComponents;
    return this;
  }

  public ParameterDTO addReferencingComponentsItem(AffectedComponentEntity referencingComponentsItem) {
    this.referencingComponents.add(referencingComponentsItem);
    return this;
  }

   /**
   * The set of all components in the flow that are referencing this Parameter
   * @return referencingComponents
  **/
  @ApiModelProperty(example = "null", value = "The set of all components in the flow that are referencing this Parameter")
  public List<AffectedComponentEntity> getReferencingComponents() {
    return referencingComponents;
  }

  public void setReferencingComponents(List<AffectedComponentEntity> referencingComponents) {
    this.referencingComponents = referencingComponents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterDTO parameterDTO = (ParameterDTO) o;
    return Objects.equals(this.name, parameterDTO.name) &&
        Objects.equals(this.description, parameterDTO.description) &&
        Objects.equals(this.sensitive, parameterDTO.sensitive) &&
        Objects.equals(this.value, parameterDTO.value) &&
        Objects.equals(this.referencingComponents, parameterDTO.referencingComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, sensitive, value, referencingComponents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterDTO {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sensitive: ").append(toIndentedString(sensitive)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    referencingComponents: ").append(toIndentedString(referencingComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

