/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.12.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.mic.nifi.swagger.client.model;

import java.util.Objects;
import at.mic.nifi.swagger.client.model.ParameterContextUpdateRequestDTO;
import at.mic.nifi.swagger.client.model.RevisionDTO;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ParameterContextUpdateRequestEntity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-05T15:38:14.826+01:00")
public class ParameterContextUpdateRequestEntity {
  @SerializedName("parameterContextRevision")
  private RevisionDTO parameterContextRevision = null;

  @SerializedName("request")
  private ParameterContextUpdateRequestDTO request = null;

  public ParameterContextUpdateRequestEntity parameterContextRevision(RevisionDTO parameterContextRevision) {
    this.parameterContextRevision = parameterContextRevision;
    return this;
  }

   /**
   * The Revision of the Parameter Context
   * @return parameterContextRevision
  **/
  @ApiModelProperty(example = "null", value = "The Revision of the Parameter Context")
  public RevisionDTO getParameterContextRevision() {
    return parameterContextRevision;
  }

  public void setParameterContextRevision(RevisionDTO parameterContextRevision) {
    this.parameterContextRevision = parameterContextRevision;
  }

  public ParameterContextUpdateRequestEntity request(ParameterContextUpdateRequestDTO request) {
    this.request = request;
    return this;
  }

   /**
   * The Update Request
   * @return request
  **/
  @ApiModelProperty(example = "null", value = "The Update Request")
  public ParameterContextUpdateRequestDTO getRequest() {
    return request;
  }

  public void setRequest(ParameterContextUpdateRequestDTO request) {
    this.request = request;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterContextUpdateRequestEntity parameterContextUpdateRequestEntity = (ParameterContextUpdateRequestEntity) o;
    return Objects.equals(this.parameterContextRevision, parameterContextUpdateRequestEntity.parameterContextRevision) &&
        Objects.equals(this.request, parameterContextUpdateRequestEntity.request);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameterContextRevision, request);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterContextUpdateRequestEntity {\n");
    
    sb.append("    parameterContextRevision: ").append(toIndentedString(parameterContextRevision)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

