/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.12.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.mic.nifi.swagger.client.model;

import java.util.Objects;
import at.mic.nifi.swagger.client.model.ComponentSearchResultDTO;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchResultsDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-05T15:38:14.826+01:00")
public class SearchResultsDTO {
  @SerializedName("processorResults")
  private List<ComponentSearchResultDTO> processorResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("connectionResults")
  private List<ComponentSearchResultDTO> connectionResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("processGroupResults")
  private List<ComponentSearchResultDTO> processGroupResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("inputPortResults")
  private List<ComponentSearchResultDTO> inputPortResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("outputPortResults")
  private List<ComponentSearchResultDTO> outputPortResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("remoteProcessGroupResults")
  private List<ComponentSearchResultDTO> remoteProcessGroupResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("funnelResults")
  private List<ComponentSearchResultDTO> funnelResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("labelResults")
  private List<ComponentSearchResultDTO> labelResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("controllerServiceNodeResults")
  private List<ComponentSearchResultDTO> controllerServiceNodeResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("parameterContextResults")
  private List<ComponentSearchResultDTO> parameterContextResults = new ArrayList<ComponentSearchResultDTO>();

  @SerializedName("parameterResults")
  private List<ComponentSearchResultDTO> parameterResults = new ArrayList<ComponentSearchResultDTO>();

  public SearchResultsDTO processorResults(List<ComponentSearchResultDTO> processorResults) {
    this.processorResults = processorResults;
    return this;
  }

  public SearchResultsDTO addProcessorResultsItem(ComponentSearchResultDTO processorResultsItem) {
    this.processorResults.add(processorResultsItem);
    return this;
  }

   /**
   * The processors that matched the search.
   * @return processorResults
  **/
  @ApiModelProperty(example = "null", value = "The processors that matched the search.")
  public List<ComponentSearchResultDTO> getProcessorResults() {
    return processorResults;
  }

  public void setProcessorResults(List<ComponentSearchResultDTO> processorResults) {
    this.processorResults = processorResults;
  }

  public SearchResultsDTO connectionResults(List<ComponentSearchResultDTO> connectionResults) {
    this.connectionResults = connectionResults;
    return this;
  }

  public SearchResultsDTO addConnectionResultsItem(ComponentSearchResultDTO connectionResultsItem) {
    this.connectionResults.add(connectionResultsItem);
    return this;
  }

   /**
   * The connections that matched the search.
   * @return connectionResults
  **/
  @ApiModelProperty(example = "null", value = "The connections that matched the search.")
  public List<ComponentSearchResultDTO> getConnectionResults() {
    return connectionResults;
  }

  public void setConnectionResults(List<ComponentSearchResultDTO> connectionResults) {
    this.connectionResults = connectionResults;
  }

  public SearchResultsDTO processGroupResults(List<ComponentSearchResultDTO> processGroupResults) {
    this.processGroupResults = processGroupResults;
    return this;
  }

  public SearchResultsDTO addProcessGroupResultsItem(ComponentSearchResultDTO processGroupResultsItem) {
    this.processGroupResults.add(processGroupResultsItem);
    return this;
  }

   /**
   * The process groups that matched the search.
   * @return processGroupResults
  **/
  @ApiModelProperty(example = "null", value = "The process groups that matched the search.")
  public List<ComponentSearchResultDTO> getProcessGroupResults() {
    return processGroupResults;
  }

  public void setProcessGroupResults(List<ComponentSearchResultDTO> processGroupResults) {
    this.processGroupResults = processGroupResults;
  }

  public SearchResultsDTO inputPortResults(List<ComponentSearchResultDTO> inputPortResults) {
    this.inputPortResults = inputPortResults;
    return this;
  }

  public SearchResultsDTO addInputPortResultsItem(ComponentSearchResultDTO inputPortResultsItem) {
    this.inputPortResults.add(inputPortResultsItem);
    return this;
  }

   /**
   * The input ports that matched the search.
   * @return inputPortResults
  **/
  @ApiModelProperty(example = "null", value = "The input ports that matched the search.")
  public List<ComponentSearchResultDTO> getInputPortResults() {
    return inputPortResults;
  }

  public void setInputPortResults(List<ComponentSearchResultDTO> inputPortResults) {
    this.inputPortResults = inputPortResults;
  }

  public SearchResultsDTO outputPortResults(List<ComponentSearchResultDTO> outputPortResults) {
    this.outputPortResults = outputPortResults;
    return this;
  }

  public SearchResultsDTO addOutputPortResultsItem(ComponentSearchResultDTO outputPortResultsItem) {
    this.outputPortResults.add(outputPortResultsItem);
    return this;
  }

   /**
   * The output ports that matched the search.
   * @return outputPortResults
  **/
  @ApiModelProperty(example = "null", value = "The output ports that matched the search.")
  public List<ComponentSearchResultDTO> getOutputPortResults() {
    return outputPortResults;
  }

  public void setOutputPortResults(List<ComponentSearchResultDTO> outputPortResults) {
    this.outputPortResults = outputPortResults;
  }

  public SearchResultsDTO remoteProcessGroupResults(List<ComponentSearchResultDTO> remoteProcessGroupResults) {
    this.remoteProcessGroupResults = remoteProcessGroupResults;
    return this;
  }

  public SearchResultsDTO addRemoteProcessGroupResultsItem(ComponentSearchResultDTO remoteProcessGroupResultsItem) {
    this.remoteProcessGroupResults.add(remoteProcessGroupResultsItem);
    return this;
  }

   /**
   * The remote process groups that matched the search.
   * @return remoteProcessGroupResults
  **/
  @ApiModelProperty(example = "null", value = "The remote process groups that matched the search.")
  public List<ComponentSearchResultDTO> getRemoteProcessGroupResults() {
    return remoteProcessGroupResults;
  }

  public void setRemoteProcessGroupResults(List<ComponentSearchResultDTO> remoteProcessGroupResults) {
    this.remoteProcessGroupResults = remoteProcessGroupResults;
  }

  public SearchResultsDTO funnelResults(List<ComponentSearchResultDTO> funnelResults) {
    this.funnelResults = funnelResults;
    return this;
  }

  public SearchResultsDTO addFunnelResultsItem(ComponentSearchResultDTO funnelResultsItem) {
    this.funnelResults.add(funnelResultsItem);
    return this;
  }

   /**
   * The funnels that matched the search.
   * @return funnelResults
  **/
  @ApiModelProperty(example = "null", value = "The funnels that matched the search.")
  public List<ComponentSearchResultDTO> getFunnelResults() {
    return funnelResults;
  }

  public void setFunnelResults(List<ComponentSearchResultDTO> funnelResults) {
    this.funnelResults = funnelResults;
  }

  public SearchResultsDTO labelResults(List<ComponentSearchResultDTO> labelResults) {
    this.labelResults = labelResults;
    return this;
  }

  public SearchResultsDTO addLabelResultsItem(ComponentSearchResultDTO labelResultsItem) {
    this.labelResults.add(labelResultsItem);
    return this;
  }

   /**
   * The labels that matched the search.
   * @return labelResults
  **/
  @ApiModelProperty(example = "null", value = "The labels that matched the search.")
  public List<ComponentSearchResultDTO> getLabelResults() {
    return labelResults;
  }

  public void setLabelResults(List<ComponentSearchResultDTO> labelResults) {
    this.labelResults = labelResults;
  }

  public SearchResultsDTO controllerServiceNodeResults(List<ComponentSearchResultDTO> controllerServiceNodeResults) {
    this.controllerServiceNodeResults = controllerServiceNodeResults;
    return this;
  }

  public SearchResultsDTO addControllerServiceNodeResultsItem(ComponentSearchResultDTO controllerServiceNodeResultsItem) {
    this.controllerServiceNodeResults.add(controllerServiceNodeResultsItem);
    return this;
  }

   /**
   * The controller service nodes that matched the search
   * @return controllerServiceNodeResults
  **/
  @ApiModelProperty(example = "null", value = "The controller service nodes that matched the search")
  public List<ComponentSearchResultDTO> getControllerServiceNodeResults() {
    return controllerServiceNodeResults;
  }

  public void setControllerServiceNodeResults(List<ComponentSearchResultDTO> controllerServiceNodeResults) {
    this.controllerServiceNodeResults = controllerServiceNodeResults;
  }

  public SearchResultsDTO parameterContextResults(List<ComponentSearchResultDTO> parameterContextResults) {
    this.parameterContextResults = parameterContextResults;
    return this;
  }

  public SearchResultsDTO addParameterContextResultsItem(ComponentSearchResultDTO parameterContextResultsItem) {
    this.parameterContextResults.add(parameterContextResultsItem);
    return this;
  }

   /**
   * The parameter contexts that matched the search.
   * @return parameterContextResults
  **/
  @ApiModelProperty(example = "null", value = "The parameter contexts that matched the search.")
  public List<ComponentSearchResultDTO> getParameterContextResults() {
    return parameterContextResults;
  }

  public void setParameterContextResults(List<ComponentSearchResultDTO> parameterContextResults) {
    this.parameterContextResults = parameterContextResults;
  }

  public SearchResultsDTO parameterResults(List<ComponentSearchResultDTO> parameterResults) {
    this.parameterResults = parameterResults;
    return this;
  }

  public SearchResultsDTO addParameterResultsItem(ComponentSearchResultDTO parameterResultsItem) {
    this.parameterResults.add(parameterResultsItem);
    return this;
  }

   /**
   * The parameters that matched the search.
   * @return parameterResults
  **/
  @ApiModelProperty(example = "null", value = "The parameters that matched the search.")
  public List<ComponentSearchResultDTO> getParameterResults() {
    return parameterResults;
  }

  public void setParameterResults(List<ComponentSearchResultDTO> parameterResults) {
    this.parameterResults = parameterResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResultsDTO searchResultsDTO = (SearchResultsDTO) o;
    return Objects.equals(this.processorResults, searchResultsDTO.processorResults) &&
        Objects.equals(this.connectionResults, searchResultsDTO.connectionResults) &&
        Objects.equals(this.processGroupResults, searchResultsDTO.processGroupResults) &&
        Objects.equals(this.inputPortResults, searchResultsDTO.inputPortResults) &&
        Objects.equals(this.outputPortResults, searchResultsDTO.outputPortResults) &&
        Objects.equals(this.remoteProcessGroupResults, searchResultsDTO.remoteProcessGroupResults) &&
        Objects.equals(this.funnelResults, searchResultsDTO.funnelResults) &&
        Objects.equals(this.labelResults, searchResultsDTO.labelResults) &&
        Objects.equals(this.controllerServiceNodeResults, searchResultsDTO.controllerServiceNodeResults) &&
        Objects.equals(this.parameterContextResults, searchResultsDTO.parameterContextResults) &&
        Objects.equals(this.parameterResults, searchResultsDTO.parameterResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processorResults, connectionResults, processGroupResults, inputPortResults, outputPortResults, remoteProcessGroupResults, funnelResults, labelResults, controllerServiceNodeResults, parameterContextResults, parameterResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResultsDTO {\n");
    
    sb.append("    processorResults: ").append(toIndentedString(processorResults)).append("\n");
    sb.append("    connectionResults: ").append(toIndentedString(connectionResults)).append("\n");
    sb.append("    processGroupResults: ").append(toIndentedString(processGroupResults)).append("\n");
    sb.append("    inputPortResults: ").append(toIndentedString(inputPortResults)).append("\n");
    sb.append("    outputPortResults: ").append(toIndentedString(outputPortResults)).append("\n");
    sb.append("    remoteProcessGroupResults: ").append(toIndentedString(remoteProcessGroupResults)).append("\n");
    sb.append("    funnelResults: ").append(toIndentedString(funnelResults)).append("\n");
    sb.append("    labelResults: ").append(toIndentedString(labelResults)).append("\n");
    sb.append("    controllerServiceNodeResults: ").append(toIndentedString(controllerServiceNodeResults)).append("\n");
    sb.append("    parameterContextResults: ").append(toIndentedString(parameterContextResults)).append("\n");
    sb.append("    parameterResults: ").append(toIndentedString(parameterResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

