/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.12.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.mic.nifi.swagger.client.model;

import java.util.Objects;
import at.mic.nifi.swagger.client.model.VariableEntity;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * VariableRegistryDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-05T15:38:14.826+01:00")
public class VariableRegistryDTO {
  @SerializedName("variables")
  private List<VariableEntity> variables = new ArrayList<VariableEntity>();

  @SerializedName("processGroupId")
  private String processGroupId = null;

  public VariableRegistryDTO variables(List<VariableEntity> variables) {
    this.variables = variables;
    return this;
  }

  public VariableRegistryDTO addVariablesItem(VariableEntity variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * The variables that are available in this Variable Registry
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "The variables that are available in this Variable Registry")
  public List<VariableEntity> getVariables() {
    return variables;
  }

  public void setVariables(List<VariableEntity> variables) {
    this.variables = variables;
  }

  public VariableRegistryDTO processGroupId(String processGroupId) {
    this.processGroupId = processGroupId;
    return this;
  }

   /**
   * The UUID of the Process Group that this Variable Registry belongs to
   * @return processGroupId
  **/
  @ApiModelProperty(example = "null", value = "The UUID of the Process Group that this Variable Registry belongs to")
  public String getProcessGroupId() {
    return processGroupId;
  }

  public void setProcessGroupId(String processGroupId) {
    this.processGroupId = processGroupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryDTO variableRegistryDTO = (VariableRegistryDTO) o;
    return Objects.equals(this.variables, variableRegistryDTO.variables) &&
        Objects.equals(this.processGroupId, variableRegistryDTO.processGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variables, processGroupId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryDTO {\n");
    
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    processGroupId: ").append(toIndentedString(processGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

